## Uncomment this line to define a global platform for your project
platform :ios, '8.0'

use_frameworks!

target ‘JSMutailTabBarItem’ do
    pod 'Alamofire'
#    pod 'SnapKit', '~> 3.2.0'
#    pod 'Kingfisher'
#    pod 'IQKeyboardManagerSwift', '4.0.10'
end




